### ISSUE TITLE
Build web framework with web interface for real-time monitoring

### ISSUE THREAD

**Issue by StefansArya** [open-source-ideas/open-source-ideas#123]
## Project description
When we developing a website, sometime we need to open `error_log` on the server and that error log wasn't been made to be accessed from URL. So we will need to open it via FTP/SFTP or write a script for viewing these files. And when the server error was DDoS-ed/brute force, the error log will become more larger and we don't have an instant button to pause the website access without shutting down the server or blocking access from nginx/apache.

So, how if we build an web interface for monitoring the system that can receive real-time notification from the server?

And... without refreshing the page to receive updates.

If there are any error, it would only increase the counter if the error was similar with another. There are some various options too for controlling the website from the web interface or mobile devices and developer can define their own controls.

We can control the website everywhere and can instantly set the website to maintenance mode if there are some dangerous error. So, we will also need to build the framework.

### Before I submitted this application
There are some similar service that offer real-time error tracking [Sentry.io](https://sentry.io/), but there are some cost if we work on a team and if you want to receive update you need to refresh the page. There are no mobile application for [Sentry.io](https://sentry.io/). The other service also has more cost too like [AirBrake](https://airbrake.io/).

### What we will use for this project?
For the admin interface we can use [BlurAdmin](https://github.com/akveo/blur-admin), so we can focus on the backend. I would suggest to develop the backend with PHP and MySQL, because almost every hosting provider have it. We will use short pooling for receiving the updates, or maybe using NodeJS's [socket.io](https://socket.io).

I want to implement it on this [web framework](https://github.com/ScarletsFiction/Scarlets). The framework have a simple structure with performance as the main priority. So if you interested you can see the progress on there.

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [x] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [x] Much work - The project will take more than a couple of weeks and serious planning is required

**Comment by KOLANICH** [comment]
>So we will need to open it via FTP

Do you really download your servers' logs via insecure ftp?

**Comment by StefansArya** [comment]
Well it's just a sample of the new web developer's background. I would add SFTP into that.

But, if you're asking about me.
I usually use Bitvise SSH Client for the FTP-SFTP bridge and open FTP port on my PC when I don't use SFTP. The FTP port can be blocked by firewall, so it's available only for localhost.
Or sometime I download the logs directly from the SFTP window.

**Comment by StefansArya** [comment]
What a surprise!
I never thought it was open source even have some paid services.

Thanks for giving me the information!
