### ISSUE TITLE
Bulk Online image viewer

### ISSUE THREAD

**Issue by Kreijstal** [open-source-ideas/open-source-ideas#135]
## Project description

[_Describe the project the best you can. Give any background information or link to resources that are necessary to understand the problem it is intended to solve. The more you elaborate on your idea, the easier it is to accomplish._]

Imagine you have around 200 url images, and you want to at least preview them, and no you don't want to download them, store in your computer why would you?

## Relevant Technology

[_Write what technology is relevant. What language, what platform, any particular library/framework/existing project it is based on?_]

Could be written in any language, but it is most effective in the browser.

## Complexity and required time

[_Please only tick off one box in each category by changing `[ ]` to `[x]`. The labels on the project will then be updated by the maintainers as soon as possible._]

### Complexity

- [x] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [x] Little work - A couple of days
- [ ] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

**Comment by KOLANICH** [comment]
I suspect it may either crash a browser or eat all the RAM on system (I still use obsolete systems with 2 GiB of RAM, and even the ones with 512 MiB of RAM).

**Comment by Kreijstal** [comment]
> I suspect it may either crash a browser or eat all the RAM on system (I still use obsolete systems with 2 GiB of RAM, and even the ones with 512 MiB of RAM).

I suspect it will if you load all images at the same time instead of implementing a pager/scroller

**Comment by louy2** [comment]
Super simple and primitive: https://view-url-images.glitch.me/

If you want to add features like grid and thumbnail and the like, feel free to remix it.

**Comment by Kreijstal** [comment]
> 
> 
> Super simple and primitive: https://view-url-images.glitch.me/
> 
> If you want to add features like grid and thumbnail and the like, feel free to remix it.

Good Job, thank you so much!
