### ISSUE TITLE
Common API for various chats

### ISSUE THREAD

**Issue by Kreijstal** [open-source-ideas/open-source-ideas#139]
## Project description

[_Describe the project the best you can. Give any background information or link to resources that are necessary to understand the problem it is intended to solve. The more you elaborate on your idea, the easier it is to accomplish._]

In essence something like smooch.io but open source, you can have a common API to different chats and platforms (WhatsApp, Discord, fb messenger, irc, slack, telegram, etc...)

The chats are basically stream of messages. You are allowed to go back and read the history programatically, but in most cases you don't need to store the history itself (except when it is IRC or the like)
You would need to provide your account credentials/API key (both should work). And a chat would be the instantiation of some "Chat" object, you can do things like:
- read your given/chosen username
- send message to another user
- send message to a channel

These objects have stream events which you can listen to, for when someone replies, types, starts typing, etc.
Conversations shouldn't be treated differently as group chats, although in many applications they have different permissions
the channels would also have flags, if they allow to embed images, if they allow to embed files, the size limit, if they allow color, if they allow markdown, etc. these probably inherit the properties from the chats.
You can also have extra features, if there are some rules in a channel, you can assign parameters to individual channels, like max_number_of_messages_in_a_row, etc.

## Relevant Technology

[_Write what technology is relevant. What language, what platform, any particular library/framework/existing project it is based on?_]

I'm sure one can find a library of any project one desires now, so it would be just matter of translating api calls

## Complexity and required time

[_Please only tick off one box in each category by changing `[ ]` to `[x]`. The labels on the project will then be updated by the maintainers as soon as possible._]

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [x] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [x] Much work - The project will take more than a couple of weeks and serious planning is required

**Comment by sebastianbarfurth** [comment]
What exactly should interaction with the API look like? What would be the setup process?

**Comment by KOLANICH** [comment]
something like pidgin,  miranda-ng, konversations and other multinetwork IM clients?

**Comment by sebastianbarfurth** [comment]
Pidgin doesn't really have "modern" integrations.
@Kreijstal How would this API work exactly?

**Comment by KOLANICH** [comment]
>Pidgin doesn't really have "modern" integrations.

https://github.com/majn/telegram-purple
https://github.com/davidgfnet/whatsapp-purple/
https://github.com/sbwtw/pidgin-wechat
https://github.com/jin-eld/tox-prpl

**Comment by remram44** [comment]
This seems to be either Pidgin (program, and libpurple, library) or Matrix (protocol and network). So I would say it's already there, and why those can certainly be improved, there is no need to start a new open-source project...

**Comment by Kreijstal** [comment]
let me design a mock api

**Comment by Kreijstal** [comment]
> This seems to be either Pidgin (program, and libpurple, library) or Matrix (protocol and network). So I would say it's already there, and while those can certainly be improved, there is no need to start a new open-source project...

I think you are right, before this I didn't know about these multinetwork im clients, and the need seems to be fulfilled for now.
