### ISSUE TITLE
JS variable bulk renamer

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/open-source-ideas#149]
## Project description
JS obfuscators tend to reuse variable (and everything else) names if their scopes don't overlap in order to break search.

This can be undone. Just descend the AST, for each scope create a mapping old var name -> new var name, where a new name is unique, and rename the vars. Then one can search the document by variables names.

## Relevant Technology
ESPrima.

### Complexity

- [x] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project

### Required time (ETA)

- [x] Little work - A couple of days

**Comment by FredrikAugust** [comment]
I'll start to work on this now.

**Comment by FredrikAugust** [comment]
https://fredrikaugust.github.io/bulk-renamer/. Constructive feedback is welcome :)

**Comment by FredrikAugust** [comment]
Github pages hasn't updated the settings yet, but it should be up _soon_.

**Comment by KOLANICH** [comment]
Thank you. I guess further discussion should go in that repo.

**Comment by KOLANICH** [comment]
BTW: https://github.com/palant/js-analysis
