### ISSUE TITLE
aria2c wget- and curl- compatible interfaces

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/open-source-ideas#150]
## Project description
Lot of CI services use shell scripts. And lot of shell scripts use wget/curl to download large files. `aria2c` does it better, but unfortunately it requires changes in shell scripts. It may make sense to create stubs for `wget` and `curl` doing the following:

1 parsing command line arguments according to the tool
2 detecting if the streams are output into stdout/stderr
3 detecting if form arguments are passed
4 use the collected info to determine if a reslurce is to be downloaded into a file on the storage
5 if the resource is downloaded into the file on the storage and if all the CLI args have an alternative in aria2c, create a cli for aria2c and invoke it, otherwise invoke the corresponding tool.

Then replace `wget` and `curl` with this tool using Debian alternatives subsystem. After that shell scripts using wget/curl would require no modification in order to work.

## Relevant Technology

* aria2c
* wget
* curl

### Complexity

- [x] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project

### Required time (ETA)

- [x] Little work - A couple of days

**Comment by louy2** [comment]
IIRC wget, curl, aria2 each have features that are not present in the others. Maybe as a starting point make a list of the common features, or the features you want to cover first?

**Comment by KOLANICH** [comment]
>IIRC wget, curl, aria2 each have features that are not present in the others.

>if all the CLI args have an alternative in aria2c

If any arg without an alternative is used, use the original tool.

>Maybe as a starting point make a list of the common features, or the features you want to cover first?

Maybe. But IMHO the starting point should be the impl of the most basic features + architecture for rewriting the stuff. Once you have the architecture, it should be easy to add anything else. But if you have a basic impl covering most of uses ("just download a file from an URI"), the app becomes immetiately useful for integration into environments.

**Comment by amirouche** [comment]
> aria2c does it better

What aria2c does better than wget or curl?

**Comment by KOLANICH** [comment]
>What aria2c does better than wget or curl?

Downloads files. curl/wget open a single connection to server and load via it, aria2c opens adjustable count (up to the hardcoded limit) of connections and loads in parallel. So, let's assumme that your PC has 30 MiB/s internet and the server throttles the speed to 3 MiB/s per connection, though supports `Range` header and doesn't throttle per combination of IP and file, so you need ~10 connections to utilize your bandwidth, and curl/wget would load 10 times slower.

**Comment by SaiHarshaK** [comment]
What exactly does stub for wget mean here?
Is there any reference to or an example for stub of a program? Like how would this program even be called when one runs the shell script?
I'm new to this and I want to try this

**Comment by KOLANICH** [comment]
Under a stub in this issue I mean an executable having the same interface cURL/wget have. I mean both command-line arguments and files formats.

>Like how would this program even be called when one runs the shell script?

Debian (and distros based on it, like Ubuntu, Kali and Mint) has a system of so-called alternatives. One can install multiple packages with the same interface and register them in the system. Then the special program `update_alternatives` would create a symlink. For example if we rename wget binary to `wget-orig` and name our stuff `wget-aria` and then register both as an alternative for `wget` and then the selected impl would be symlinked to `/usr/bin/wget`.

>Is there any reference to or an example for stub of a program? 

I guess no. Here is an approximate plan of your work:
1. install curl, wget, aria2c
2. create a mapping of MVP features of each program to each other
3. select the programming language. I recommend either c++2a, or python. You may also find rust and go useful. The programming language should not require any runtime not present in every distro, so JVM- and .Net-based languages and JS are poor choices here.
4. select a good library for building command line interfaces.
5. create structs representing tool-agnostic state of CLI which is a superset of all the features needed to be implemented. I mean that all the tools allow to download a file into a specific dir, so we may need an object representing downloading of that file, so it should contain a collection of source URLs and the destination path (not dir, but file name).
6. create the code parsing CLI args into these structs
7. create the code emitting new CLI args for the selected tool from the structs.

**Comment by SaiHarshaK** [comment]
https://github.com/SaiHarshaK/aria2c-for-wget-curl. Only the wget stub is done as of now :)

**Comment by SaiHarshaK** [comment]
@KOLANICH for the wget-stub, i made it so that in case it's not able to parse the cmd to aria2c equivalent, it would execute wget instead.

**Comment by KOLANICH** [comment]
Thanks! Let's do the future discussion in the projects repos.

**Comment by SaiHarshaK** [comment]
Are there any requirements for a project to go Hall of Fame in the project's README.md?

**Comment by FredrikAugust** [comment]
Only that it's completed @SaiHarshaK. If this is completed, I can add it when I have time, or you can create a pull request to add it to the README :)

**Comment by SaiHarshaK** [comment]
I see will do that.

**Comment by famewolf** [comment]
aria2c-for-wget-curl does not appear to be available for Arch users and the setup.py doesn't appear to work.  It changes the cursor to some sort of selection similar if I was going to run xkill and select a window.   I'd like to use the wrapper for curl and wget.  I use 5G for internet and multiple connections always do better than single ones.
