### ISSUE TITLE
COMPLETED.md 2nd project 404s

### ISSUE THREAD

**Issue by Kreijstal** [open-source-ideas/open-source-ideas#162]
The second project that solved issue #11 on the [COMPLETED.md](https://github.com/open-source-ideas/open-source-ideas/blob/master/COMPLETED.md) is a dead link, and the repository doesn't exist anymore.

**Comment by Kreijstal** [comment]
On some investigation the project does exist but now is called joyread instead of libreread
https://github.com/joyread

**Comment by remram44** [comment]
Seems like an issue which should have been filed against [meta](https://github.com/open-source-ideas/meta), it's not an open source idea 😉

**Comment by Kreijstal** [comment]
I didn't know this
