### ISSUE TITLE
Websocket testing tool like Postman

### ISSUE THREAD

**Issue by drex44** [open-source-ideas/open-source-ideas#175]
## Project description

I have been looking for a tool like Postman to test websockets.

## Relevant Technology

- GraphQL
- NodeJS

### Complexity

- [x] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology

### Required time (ETA)

- [x] Much work - The project will take more than a couple of weeks and serious planning is required

**Comment by derhuerst** [comment]
FYI: [`wsd`](https://github.com/alexanderGugel/wsd), [`wsc`](https://github.com/danielstjules/wsc) and [`websocat`](https://github.com/vi/websocat) are similar.

**Comment by drex44** [comment]
@derhuerst Exactly like you mentioned but I was thinking about more of a tool in lieu with Postman. For example, I want my testing team to test Websockets same how they test APIs. They want a GUI with features as to save a connection, create multiple connections, and also be able to share a collection like Postman.

**Comment by remram44** [comment]
Seems a duplicate of https://github.com/postmanlabs/postman-app-support/issues/4009: Postman is already considering the feature, and is probably the right place to have this. Readers, please contribute to Postman instead of making a new tool as requested by @drex44

**Comment by drex44** [comment]
1. @remram44 you are absolutely right. I also searched the same thing and came to the same issue you mentioned but it is just a feature request repo and it doesn't have any code of the app. One cannot contribute to the development of the feature. 
2. So instead of waiting for the Postman team to build it, I thought about developing and possibly help the community. 
3. Developing it open source means if Postman wants to use the same code and integrate it into their app, It would be a win-win situation. In the end, the community will get a great tool to work with, be it either a new tool or as new functionality in Postman.

**Comment by rafaelfcsouza** [comment]
have you checked insomnia?
https://github.com/getinsomnia/insomnia

**Comment by remram44** [comment]
Insomnia does not support websockets either: https://github.com/getinsomnia/insomnia/issues/528

**Comment by drex44** [comment]
Just letting everybody know that I have started working on this one. Named it **Martian** (Apparently it will exist only until same feature arrives in Postman).

**Reviews/Suggestions are highly appreciated! :)**

Repo link: [drex44/martian](https://github.com/drex44/martian)

**Comment by minarch91** [comment]
меня потому что я мечтаю создать монету для Справедливости.Разработка и кодирование децентрализованной,саморегулируемой криптовалюты.Экономика которой является надежным и беспроигрышным решением базирующемся на трансформации ,,до судебно распределённого  , 100% Морального ущерба,(моральных потерь-убытка)>>трансформация>> в Материальные доходы. Я мечтаю о платформе для каждого пользователя блокчейна и криптовалюте на основе ETH которая может представлять собой универсальное приложение для запуска различных(национальных) квалификаций токенов,базирующихся на специализированных(национальных) смарт-контрактах,облегчающих нагрузку на национальные системы уголовного и гражданского правосудия ,толкающих(делающих выгодным) двигаться в сторону Справедливости на основе ,до судебной, гражданской пере адресации-распределении 100%-ов Морального ущерба, в смарт-контракте.Экономика Токена-справедливости становится привязанной к > общественной организации > моральному ущербу >Справедливости> банку. Я очень хотел бы чтобы Вы помогли мне с построением и оптимизацией алгоритма сети а также обширной практики настройки параметров алгоритма,чтобы было правильно. Всё это требует глубокого,детального понимания кода,который я надеюсь построить под Вашим руководством. Я прошу учиться у Вас и хочу достичь, в партнерстве с Вами ,взаимопонимания. minarch91.09.04.2019, 22:11, "Remi Rampin" <notifications@github.com>:Insomnia does not support websockets either: getinsomnia/insomnia#528

**Comment by asleepysamurai** [comment]
For those of you who want this, I built Socket Wrench for this exact purpose. It supports

- multiple concurrent connections to servers (with all responses and connections displayed in the same view),
- comprehensive message history to enable easy re-use of messages, and
- custom headers for the initial connection request.

It's available for Mac OS X, Windows and Linux and you can get it from [here](https://asleepysamurai.com/articles/socketwrench?ref=github/open-source-ideas/issues/175).

**Comment by veaceslav3** [comment]
@drex44 you can try using https://app.gosandy.io/
