### ISSUE TITLE
GPU-Accelerated Framerate Conversion

### ISSUE THREAD

**Issue by BrimsonBhin** [open-source-ideas/open-source-ideas#177]
## Project description

My idea is an application that can convert a video's frame-rate through OpenGL-accelerated optical flow.

A developer named **_sesse_** achieved realtime slow-motion using OpenGL 4.5 in his [futatabi project](https://nageru.sesse.net/doc/futatabi.html). [This 2019 FOSDEM video clip](https://youtu.be/b4WHGwBgAbQ?t=890) demonstrated the results. **_sesse_** is also the developer of [Movit, a library for OpenGL video effects](https://movit.sesse.net/).

### Why do people need such an application?

**Leisure/Hobbies**
- People who can not afford high-speed cameras or desktop computers to achieve genuine slow-motion. This is why many non-linear editors have their own implementation of an optical-flow slow-motion effect.
- People who like to see their content in a higher frame-rate.

**Restoration:** Some videos were recorded in a low frame-rate. FRC through optical flow can help "restore" video framerates into something tolerable and smooth to watch.

**Research:** People can fork this project to integrate and test their own optical flow algorithms for academic or recreational purposes.

### Languages that may be used for this project

- C++
- OpenGL
- OpenCL

### Software I will mention

[**butterflow**](https://github.com/dthpham/butterflow): Cross-platform, Python-based CLI application for OpenCL-accelerated slow-motion. A [seperate GUI application](https://github.com/wagesj45/butterflow-ui) is also available for butterflow.

[**slowmoVideo**](https://github.com/slowmoVideo/slowmoVideo): C++ standalone application for slow-motion video. SlomoVideo is one of the only open-source alternatives to Twixtor, a plugin for motion interpolation.

[**VapourSynth MVTools**](https://github.com/dubhater/vapoursynth-mvtools): Cross-platform [Vapoursynth](https://github.com/vapoursynth/vapoursynth) plugin written in C and C++ for motion compensated effects such as slow-motion, degrain, and motion-stabilization.

### ISSUES

I wrote this issue because I have not seen an open-source framerate-converter (FRC) that is:

- **Not CUDA-based:** People with non-Nvidia GPUs cannot test the plethora of GPU-accelerated optical flow projects from GitHub, unless they like software rendering

- **Maintained:** _ButterFlow_ and _slomoVideo_ will not work on Linux distributions in the future due to outdated dependencies. Both projects are abandoned at this point and still have bugs.

- **Not slow:** _VapourSynth MVTools_ is completely CPU dependent and relies on SSE/AVX optimizations for performance. Therefore, HD video inputs **dip** MVTools' performance because graphics-related work do not offload onto other hardware.
  - There were discussions on Doom9 about a hypothetical, GPU-based MVTools. However, MVTool's code-base was complex to rewrite and potential memory bottlenecks were an issue.
  - Despite using OpenCL, _ButterFlow_ is **even slower** than CPU-exclusive MVTools. This may be due to the encoding phase of interpolation.

- **User friendly:** Most open-source FRC applications either require compiling software or learning functionalities of different software.
  - For example, I had to learn a bit of [Vapoursynth's python scripting](http://www.vapoursynth.com/doc/pythonreference.html) before interpolating my video. Not a a big issue in my opinion.

<br>

### Standalone Applications

[**futatabi**](https://nageru.sesse.net/doc/futatabi.html): An open-source Linux application for multi-camera instant replay with real-time slow motion through optical flow. Coded with C++ and OpenGL.

[**SmoothVideoProject (SVP)**](https://www.svp-team.com/wiki/Main_Page): Closed-source software suite dedicated to frame-rate interpolation. The project was based on MVTools' GPL code [they made $40,000 out of](https://www.indiegogo.com/projects/real-time-video-frame-rate-conversion-for-pc#/).

[**FFmpeg's Minterpolate filter**](https://ffmpeg.org/ffmpeg-filters.html#minterpolate): FFmpeg's libavfilter filter written in C for motion interpolation. [source code](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_minterpolate.c)

### Libraries/Plugins

[**PixelFlow**](https://github.com/diwi/PixelFlow): A [Processing](https://processing.org/reference/environment/)/Java library for high performance GPU-Computing (GLSL). Optical flow could be done through GLSL as demonstrated in this [PixelFlow showcase](https://vimeo.com/184850333)

[**ofxFlowTools**](https://github.com/moostrik/ofxFlowTools): C++ [openFrameworks](https://github.com/openframeworks/openFrameworks) addon that "combines 2D fluid simulation, optical flow and more using GLSL shaders".

<br>

### Complexity

- [X] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [x] Much work - The project will take more than a couple of weeks

<br>

### Futatabi

- [sesse's FOSDEM video on Futatabi's real-time interpolation](https://www.youtube.com/watch?v=b4WHGwBgAbQ)
  - [Slideshow transcript of video](https://nageru.sesse.net/futatabi-fosdem2019-with-notes.pdf)
- [Documentation](https://nageru.sesse.net/doc/futatabi.html#)
- [Website](https://nageru.sesse.net/)

### ofxFlowTools

- [Forum announcement and introduction video](https://forum.openframeworks.cc/t/ofxflowtools-optical-flow-fluid-dynamics-and-particles-in-glsl/15470)
- [Source code](https://github.com/moostrik/ofxFlowTools)

### PixelFlow

- [Optical flow example](https://vimeo.com/184850333)
- [Source code](https://github.com/diwi/PixelFlow)

**Comment by FredrikAugust** [comment]
This sounds amazing! Great idea 💡
