### ISSUE TITLE
Morphable and tweakable hashtables/dictionaries for python

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/open-source-ideas#191]
## Project description

I am writing a python lib for data processing, cleansing (includes aggregating separate datasets and detection anomalies). I have already implemented preprocessing framework. The data are preprocessed, to each row an identifier (a tuple of strings) is assigned. Then we want to lookup the data by any prefix fast.

But as I understand there are some issues.

A naïve way to do it is to just use dicts.

```python

index = {}

for rec in records:
    k = rec["key"]
    parent = index
    for pc in k[:-1]:
        if pc not in parent:
            parent = parent[pc] = {}
        else:
            parent = parent[pc]
        parent[k[-1]] = rec
```
     

But it has some problems. Not very severe ones, since the data I currently deal with is small enough, but python dicts have several disadvantages

1. inserts are not O(1). Because inserts to a hashtable are not O(1) (it is a misconception that hashtables are O(1) containers).
2. lookups when inserting are not O(1) due to the same reason.
3. multilevel hashtables are used, so waste of memory

there is ain't no such a thing as free lunch, so the following disadvantage is

4. no way to provide prior beleifs about the nature of keys. More precisely lookup to insert ratio for each index level. Usual pattern: parts of multikey in its beginning are more general and looked up lot more than inserted. Parts in the end of multikey are almost never looked up during hashtable building, but are constantly inserted.

Index levels with lot of lookups can be optimized by rebuilding the table on each insert with perfect hashing. It is not O(1), but when there are many lookups and no inserts (assumming small count of unique keys on first level relatively to overall count of records the probability of inserting will be small and probability of succesful lookup will be 1-probability of insert).

Index layers with lot of insertions (the last layers into which unique keys are inserted, the situation is another, probability of succesful lookup is ~0, so is the probability of key (not hash) collision) can be optimized by using chains, storing in each bin pointer to list last element and doing partial lookup only. Under partial lookup I mean lookup only by hash without conflict resolution, which involves walking the chain and comparing each element. So we just find a bin and insert element into its list for O(1). Duplicate keys will be resolved later by aggregation function, so we really need to store them, but there should be a fast way to find them. For example we can qsort the list for O(n*log n) and then walk it for O(n).

After inserting the hashtable can be rebuilt to optimize lookups and iteration. I mean we need to iterate by layers. This can be combined to elimination of hierarchical hashtables. We need a hash function which is not very random in the sense it maps multikeys having the same prefix to the numbers in a range `[a, a+b]`, where `a` is a hash of prefix.

Also we would like to have it persistent on disk. Kind of a key-value storage, but hierarchical.

## Relevant Technology
* python C extensions
* computer science

### Complexity

- [x] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project

### Required time (ETA)

- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [x] Library

**Comment by remram44** [comment]
It seems to me that you want a trie? Not sure, your example is not very readable (what is 'key'?)

This should be easy to implement, and you can use something like Cython to make it faster if you need to.

Because it's a common data structure, there are also existing libs for that, but I'm not sure how efficient or complete they are ([marisa-trie](https://github.com/pytries/marisa-trie), [python-trie](https://github.com/bdimmick/python-trie), [PyTrie](https://pypi.org/project/PyTrie/))

**Comment by KOLANICH** [comment]
>It seems to me that you want a trie?

Hmmm.., probably I really want it! Thank you! 

>what is 'key'?

In my case it is usually a string. A `multikey` in my case is a `tuple` of keys..
