### ISSUE TITLE
Open Computing - Skynet sans Intelligence

### ISSUE THREAD

**Issue by aakashsinghbais** [open-source-ideas/open-source-ideas#205]
## Project description

To create a system to harness the computational power of idle computing devices like mobile phones and computers volunteering in this system. The idle computational power will be used towards helping build a global virtual computer with the total processing power equivalent to several super computers and will be used to help the scientific community/organisations lacking such computational power/other deserving projects or organisations voted for by the volunteers volunteering in the system.<br>
Participants from the general public with their idle devices plugged in to the internet and connected to this network will volunteer with the processing power of their device.<br>
The system will NOT have an AI of its own so everything will remain safe from Singularities and Skynets!!

## Relevant Technology

I am not very sure of the programming languages or technologies that will be required to implement this.

## Complexity and required time

This project should require serious effort from professionals.

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [x] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [x] Mobile app
- [ ] IoT
- [ ] Web app
- [x] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [x] Security
- [x] Blockchain
- [x] Futuristic Tech/Something Unique

**Comment by KOLANICH** [comment]
What will make people to spend own money and battery charge on that?

**Comment by aakashsinghbais** [comment]
Money and battery charge are not a problem for everyone. For example educational institutions often have computer labs with hundreds of computers which remain switched on 24×7 (unless a student is responsible enough to switch them off after using). So, since we don't expect these computers to sleep and dream at night as we do...what do they do when nobody is around to use them? Well, they keep whirring and screaching anyways - some of them do go to sleep but not all are equally obedient. More over many a times we have mobile devices which are of no use to us because either their screen has got slightly damaged or a few buttons are not working, but in most cases the hand set which are thrown away have their processors in working condition, so people may want to put them to good use by helping the community...and after all, why do people participate and contribute in open-source projects is mainly because they feel good to help the community and human kind move ahead. Satisfaction is key. But, even if still some driving force should be required, we can use a blockchain with cryptocurrency. The organisations being helped can voluntarily pump extra money into the system to keep it running, as long as it costs significantly less than buying a supercomputer of their own and maintain it and keep it in good health, the organisations utilising this global network will be very happy to contribute a bit to pay the volunteers I guess. Then, it will become something similar to mining bitcoins - only it will be for a great cause! Thanks for the comment!

**Comment by remram44** [comment]
[BOINC](https://github.com/BOINC/boinc) is open-source (GPL)

**Comment by KOLANICH** [comment]
>For example educational institutions, government offices etc. often have computer labs with hundreds of computers which remain switched on 24×7 (unless a student/user is responsible enough to switch them off after using).

turned on doesn't mean consuming the same power when 100% utilized. Modern computers are interrupt driven, most of the time they sleep. You can approximate the consumed power by heat dissipation. When computers compute they are hot. When they are idle the are pretty cool.

**Comment by aakashsinghbais** [comment]
Yes, I agree. Thanks.
