### ISSUE TITLE
Terminal program that takes description of character and searches for character/emoji/cjk

### ISSUE THREAD

**Issue by Kreijstal** [open-source-ideas/open-source-ideas#207]
## Project description
Imagine you want to search for an emoji but you dont want to boot up a GUI terminal program or browse the web but can get directly search through description or browse the character code from the terminal

could work like this: 

$ unicode --emoji sushi
:sushi: 
$

## Relevant Technology

could be a bash file or something more advanced
### Complexity

- [x] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [x] Little work - A couple of days
- [ ] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [x] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [x] Futuristic Tech/Something Unique

**Comment by jri-sp** [comment]
Something like this https://github.com/b4b4r07/emoji-cli ?

**Comment by Kreijstal** [comment]
> Something like this https://github.com/b4b4r07/emoji-cli ?

That doesn't return the emoji just the `:emoji-name:` but yes, ideally it would be nice if you could somehow interact with it to get the character that you want

**Comment by derhuerst** [comment]
There's also [`chars`](https://github.com/antifuchs/chars).

**Comment by KOLANICH** [comment]
also python `unicodedata` module.

**Comment by ItsNickBarry** [comment]
I've added a CLI to my emoji suggestion library.  See [here](https://github.com/ItsNickBarry/emojideas).  Search is based on keywords as well as character name, and there's a `fuzzy` option.

**Comment by FredrikAugust** [comment]
I added developer tooling to this as well, as most people who use the command line are developers, and I think it would be helpful for quite some people looking to add emojis to their code or similar (and don't own a computer with an emoji-insertion feature).

**Comment by Kreijstal** [comment]
There is also [unicode.vim](https://github.com/chrisbra/unicode.vim)

there turns out to be already too many existing tools, so I'm thankful for that, and the tools people posted here, I dont think there is a need for this tool anymore
