### ISSUE TITLE
A GUI for exploring HTTP Archive files

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/open-source-ideas#211]
## Project description

It is possible to capture HTTP conversations into HAR files with devtools available in browsers and third-party tools like mitmproxy.

But it is inconvenient to explore them with a text editor because redundant info is saved (that is the same for all the requests) and often in base64, so they are large. And the tools lack the feature to load the captures.

HAR files are just JSON of a [certain schema](https://github.com/ahmadnassri/har-schema). They contain info about HTTP headers, responses and requests content.

We need the features present currently in Firefox devtools, + some more and as a standalone app.

Additional features needed:

* generation of source code in different languages replaying the requests
* linking identifiers present in headers and structured (application/x-www-form-urlencoded, json, xml, something-separated values, etc) requests and responses to each other and visualizing them as a graph
* putting user-configurable fields of headers/structured requests/responses into a grid view in the right as a column

## Relevant Technology

* Qt5
* python
* mitmproxy

### Complexity

- [x] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
### Required time (ETA)

- [x] Little work - A couple of days

### Categories

- [x] Developer Tooling

**Comment by FredrikAugust** [comment]
This is a really good one I use at work: https://toolbox.googleapps.com/apps/har_analyzer/.

**Comment by FredrikAugust** [comment]
Apparently, you also have [this one](http://www.softwareishard.com/har/viewer/), but I prefer Google's.

**Comment by numan98khan** [comment]
I am really interested in this project but it seems that such a solution already exists. So is this issue going to be closed or is there still innovation we could achieve here?

**Comment by KOLANICH** [comment]
>is there still innovation we could achieve here?

Innovation? No. But rewriting that in C++ just to stay away of Node and NPM won't harm.

But to rewrite
