### ISSUE TITLE
AI alone with the Periodic Table

### ISSUE THREAD

**Issue by gabrielt-prathivys** [open-source-ideas/open-source-ideas#214]
Hello everybody.
I'm starting with programming, i'v worked with art, design and health. Well, i said that because i can have a very different point of view, and some (many) ideas, but can't execute.

I'v seen a lot of papers about AI:
Until now no one has created a neural network, or game, where the lego pieces are the elements of the periodic table. Reaction and responses? linnus pauling electron interactions: acctually every combination of eletronic layers is already cataloged.

I just can imagine...cenarios: like a drop of acid in a peace of metal (right corrosive intensity, right alloy properties) triyng to pass through. Let the AI try to stop it, if pass through the process re-starts to the next gen.

Let's leave the AI learning to use every element, simple mixtures to atomic fusion, quarks in the future maybe? strange matter...well, we already know how to get to the nucleus of a neutron star where came from every dense material.

 That is very far away, but if we get to the carbon - enzimes - molecules of deseases or alloys with graphene we already can create and solve some things.

Sorry the accent, i'm Brazilian...with so much ideas, this is just a test.

Let's the game begins, i hope who see this send to more people and viralize the idea.

Thanks a lot, and Cheers.

P.s. Thinking about start with some sort of library of subjects (Chemistry) like that they used in: https://www.youtube.com/watch?v=wvsE8jm1GzE

P.p.s Krypton image attached is the fuel of the Elon Musk Starship

![Krypton-krypton-symbol-square-properties-some-periodic](https://user-images.githubusercontent.com/57564460/70674732-b01a2700-1c65-11ea-91e2-b432601686a1.jpg)
![atoms](https://user-images.githubusercontent.com/57564460/70674751-b8726200-1c65-11ea-8b6e-05d875605330.png)
![layers](https://user-images.githubusercontent.com/57564460/70674759-bdcfac80-1c65-11ea-84a4-9ba605b03066.png)
![spins](https://user-images.githubusercontent.com/57564460/70674773-c6c07e00-1c65-11ea-8cff-aa8b9171b8f4.png)
![coordinations](https://user-images.githubusercontent.com/57564460/70674784-cd4ef580-1c65-11ea-95be-0858172ee83d.gif)

**Comment by remram44** [comment]
This is a research question and not an easy one 😅 not really an open-source program. You might want to apply for a PhD student position if you are really interested in the question, honestly. Regardless, I'm sure there has been attempts in the area, but I would wager that acquiring enough data for any meaningful training is more difficult than you think, because physics at this level of not completely understood (and can't really be acquired an other way that simulation, we can't 3D print atoms either).

**Comment by gabrielt-prathivys** [comment]
Lets see if other opinions shows up.
Acctualy, i can't imagine any better use to AI then manipulate molecules with one outcome, or create some structures interacting with real material properties. Some people are trying to sistetize material but only with 3D rendering purpose for gaming. And we already print WiTh Atoms, like the IBM logo.
 But thank you for you time.
![IBM_in_atoms](https://user-images.githubusercontent.com/57564460/70677835-0b9ce280-1c6f-11ea-85f2-05154ab45961.gif)

**Comment by KOLANICH** [comment]
>And we already print WiTh Atoms, like the IBM logo.

Only if you have access to a high vacuum STM.

**Comment by FredrikAugust** [comment]
Wow, cool and unique idea. Hope you are able to create this!

**Comment by MarchWorks** [comment]
It will be great if someone splits this idea into milestones

**Comment by gabrielt-prathivys** [comment]
> It will be great if someone splits this idea into milestones

Hi March! Thank you for the promptitude. I was just testing the responses from the community, i really appreciate that.

I don't even know how to set the milestones here in the site, but i will look for it.
let me think about it...and give me what you saw in your imagination too, please.

Maybe:
1)  Create a visual interface for the atom? Spheres around Spheres? no setting for spins (that can be in a second moment)
2) Create a Set of atoms that can interact, a MVP...we can start with Hidrogen, Oxigen and try to make than interact becoming water? just 3 Balls with magnets bending to H20.
3) After Water we can try other Stuffs in the middle of water, mixing acids and letting then find balance.
I know is not the AI yet, with this simple environment we can start asking solutions with a simple kit of atoms to the AI use it.

**Comment by gabrielt-prathivys** [comment]
let me think about it...and give me what you saw in your imagination too, please.

Maybe:

Create a visual interface for the atom? Spheres around Spheres? no setting for spins (that can be in a second moment)
Create a Set of atoms that can interact, a MVP...we can start with Hidrogen, Oxigen and try to make than interact becoming water? just 3 Balls with magnets bending to H20.
After Water we can try other Stuffs in the middle of water, mixing acids and letting then find balance.
I know is not the AI yet, with this simple environment we can start asking solutions with a simple kit of atoms to the AI use it.

**Comment by losnol** [comment]
Hello! I'm interested. I'm planning on starting a master course on Machine Learning on Biology (and this work can be nice to model some protein molecules). Also, I'm studying software engineering, agile and I can help with the prototype. Also I can translate the business model into the software. And I'm brazilian too : D (so... sorry for the english too!  xD ) . How is the status of this idea? If you have some plans or a good picture of all in your mind, I can start to model this.

Thanks in advance!

**Comment by gabrielt-prathivys** [comment]
> Hello! I'm interested. I'm planning on starting a master course on Machine Learning on Biology (and this work can be nice to model some protein molecules). Also, I'm studying software engineering, agile and I can help with the prototype. Also I can translate the business model into the software. And I'm brazilian too : D (so... sorry for the english too! xD ) . How is the status of this idea? If you have some plans or a good picture of all in your mind, I can start to model this.
> 
> Thanks in advance!

Hi, it will help a lot if we can talk some details in portuguese, you can send me an e-mail, or any one interested, on gabrielt.prathivys@gmail.com

 I'm very conservative about how to start, as business manager i can tell that the foundation provide the results...
 Lets think about strategies to get there, you are the early ecangelist of the ideia, after we get together it will become a snow ball as people undestand what is our proposal (i really believe that people with exclusive tech background read this post and don't get  what it means the AI create something with the elements...something that reacts with a enzime, or a cancer, or create some sort of molecule that reacts do carbon gas realeasing oxygen after creating eletric energy).
 1) We need suport of 2-3 people from chemistry, i can look in forums, do you know some one from your university? (Where do you live?)
2) I have know idea of what can happens after a beta 0.0.0.1 work, do you read something here in Git about saving the origins of the idea?
3) we have to start from basics, whats we learn first in high school? What is an atom, electron, neutron, diferent atomic weights of mass, and eletronegativity (atraction and repulsion) of eletrons in diferent eletronic layers...this will be our interface for everything else, where the AI can try to beat the "score" stabilyzing or destroying some groug of atoms mixed (molecules).
# any ideia of how to star that? We literally need lots of balls here.

Cheers

**Comment by remram44** [comment]
You guys really think you can solve [computational chemistry](https://en.wikipedia.org/wiki/Computational_chemistry) on your own, or even come close to the state of the art?

**Comment by losnol** [comment]
> Hi, it will help a lot if we can talk some details in portuguese, you can send me an e-mail, or any one interested, on [gabrielt.prathivys@gmail.com](mailto:gabrielt.prathivys@gmail.com)
> 
> I'm very conservative about how to start, as business manager i can tell that the foundation provide the results...
> Lets think about strategies to get there, you are the early evangelist of the ideia, after we get together it will become a snow ball as people undestand what is our proposal (i really believe that people with exclusive tech background read this post and don't get what it means the AI create something with the elements...something that reacts with a enzime, or a cancer, or create some sort of molecule that reacts do carbon gas realeasing oxygen after creating eletric energy).
> 
> 1. We need suport of 2-3 people from chemistry, i can look in forums, do you know some one from your university? (Where do you live?)
> 2. I have know idea of what can happens after a beta 0.0.0.1 work, do you read something here in Git about saving the origins of the idea?
> 3. we have to start from basics, whats we learn first in high school? What is an atom, electron, neutron, diferent atomic weights of mass, and eletronegativity (atraction and repulsion) of eletrons in diferent eletronic layers...this will be our interface for everything else, where the AI can try to beat the "score" stabilyzing or destroying some groug of atoms mixed (molecules).
> 
> # any ideia of how to start that? We literally need lots of balls kicking up here.
> Cheers

I'll send a e-mail. 

I know some people that work with Chemical Engineering. I think a good start is the Standard Model of particle physics for interactions. Because what we see in high school normally isn't totally compatible with this state of art model. Basically it's a chess game. 3 main classes of particles (quarks, leptons, bosons) and 3 of 4 main universal forces (electromagnetism, weak and strong nuclear force).

 It's a very complex problem, involving numeric calculus and differential equations. Probably we'll need a stochastic approach (like Monte Carlo) and a paralel programming. We have to work GPU or FPGA based programming, since it'll have the paralel thing. 

I have a idea how to make the business model and put into some documentation on git.

**Comment by losnol** [comment]
> You guys really think you can solve [computational chemistry](https://en.wikipedia.org/wiki/Computational_chemistry) on your own, or even come close to the state of the art?

I don't know if I can come close to the state of art. But I'll try to do a decent model and put into open source. ML It's my area of reseaech, and maybe I can model something. With open source, maybe some people can help with this complicated problem too. So it's a hard question to answer at the moment.

**Comment by gabrielt-prathivys** [comment]
> > You guys really think you can solve [computational chemistry](https://en.wikipedia.org/wiki/Computational_chemistry) on your own, or even come close to the state of the art?
> 
> I don't know if I can come close to the state of art. But I'll try to do a decent model and put into open source. ML It's my area of reseaech, and maybe I can model something. With open source, maybe some people can help with this complicated problem too. So it's a hard question to answer at the moment.

Your both answers here and in my post show me exactly that you are the kind of people that can make it happens, i don't even know any language of programming, but i'm in the biggest community in the world...i what a project in that bunker in the artic too, people to help will appear, just lets talk talk and talk about good ideas and sketch something, its better a draw then nothing.
And @remram44 , you are what we need, the no, why do you think it is impossible? because in that imagination of what we will need its the point that we need to solve, i know the big picture: equipment, money etc, but resume what you see, what i need to find to a team start here?

Any one else? HI WORLD!?

P.s. looking foward, how can i create the milestones here? And it will look foolish but i will draw something and we can put the meat over the bones.

**Comment by gabrielt-prathivys** [comment]
> > You guys really think you can solve [computational chemistry](https://en.wikipedia.org/wiki/Computational_chemistry) on your own, or even come close to the state of the art?
> 
> I don't know if I can come close to the state of art. But I'll try to do a decent model and put into open source. ML It's my area of reseaech, and maybe I can model something. With open source, maybe some people can help with this complicated problem too. So it's a hard question to answer at the moment.


I found a """Game""" ready:
https://en.wikipedia.org/wiki/GAMESS_(UK)

It´s in C, but there is a lista on Wiki with molecular programs in Python.
Most of then are free, should we ask the code?
And our meeting tomorrow on skype? received my e-mail? if you cant choose any day in the morning.

Cheers!

**Comment by losnol** [comment]
> > > You guys really think you can solve [computational chemistry](https://en.wikipedia.org/wiki/Computational_chemistry) on your own, or even come close to the state of the art?
> > 
> > 
> > I don't know if I can come close to the state of art. But I'll try to do a decent model and put into open source. ML It's my area of reseaech, and maybe I can model something. With open source, maybe some people can help with this complicated problem too. So it's a hard question to answer at the moment.
> 
> I found a """Game""" ready:
> https://en.wikipedia.org/wiki/GAMESS_(UK)
> 
> It´s in C, but there is a lista on Wiki with molecular programs in Python.
> Most of then are free, should we ask the code?
> And our meeting tomorrow on skype? received my e-mail? if you cant choose any day in the morning.
> 
> Cheers!

I think that, if possible, we should stick with open source libraries. But I think is worth to check it, and maybe explain the situation. in most of academic code, there's some "reaserch only distribution". So I don't know if they're willing to share some code to the project.

**Comment by gabrielt-prathivys** [comment]
> > > > You guys really think you can solve [computational chemistry](https://en.wikipedia.org/wiki/Computational_chemistry) on your own, or even come close to the state of the art?
> > > 
> > > 
> > > I don't know if I can come close to the state of art. But I'll try to do a decent model and put into open source. ML It's my area of reseaech, and maybe I can model something. With open source, maybe some people can help with this complicated problem too. So it's a hard question to answer at the moment.
> > 
> > 
> > I found a """Game""" ready:
> > https://en.wikipedia.org/wiki/GAMESS_(UK)
> > It´s in C, but there is a lista on Wiki with molecular programs in Python.
> > Most of then are free, should we ask the code?
> > And our meeting tomorrow on skype? received my e-mail? if you cant choose any day in the morning.
> > Cheers!
> 
> I think that, if possible, we should stick with open source libraries. But I think is worth to check it, and maybe explain the situation. in most of academic code, there's some "reaserch only distribution". So I don't know if they're willing to share some code to the project.

I'v made contact with all the Free/Open softwares, looking the ones made in Python, i'm shure they will be glad to help, not only with the codes (that some is actually already opened) but giving some advices and beign updated for further suggestions and upgrades. 

The sticks are connecting, maybe this pile can be a tower.
From nothing to 70%?? Do you know any algorithm or system, or clue of where to search an already machine learning system that we can adapt? 80%?

**Comment by KOLANICH** [comment]
If one needs a free open source quantum chemistry simulator, one of the few having GPU acceleration is cp2k. But quantum chemistry suites won't replace human domain knowledge, the hyperparameters have to be set by a human. Among the most important ones are pseudopotentials - approximations of a nuclei potentials which main purpose is to optimize computation making it feasible and which were carefully crafted. But models and approximations are just models and approximations. You must understand them well to apply them correctly. Otherwise you get garbage.

**Comment by gabrielt-prathivys** [comment]
Thaks a lot for your opion and paticipation, we will save it and use it in the right moment.
 All of you have much more expertise then me, i see it so simples, because all that ajustments and variables, can be updated  in further upgrades by the community.

I realky just whats to change the dinossaurs and cars from games in machine learning tests, to balls with some sort of magnectic atraction and repulsion, give the task and see the machine connect the dots, maybe make "rustic" water H2O, everything  else is a gap that we can fill with whatever you whats.

 I simple question, someone imagine how the AI can paky with this balls and their electrons in a productive way as a child game?

**Comment by losnol** [comment]
> Thaks a lot for your opion and paticipation, we will save it and use it in the right moment.
> All of you have much more expertise then me, i see it so simples, because all that ajustments and variables, can be updated in further upgrades by the community.
> 
> I realky just whats to change the dinossaurs and cars from games in machine learning tests, to balls with some sort of magnectic atraction and repulsion, give the task and see the machine connect the dots, maybe make "rustic" water H2O, everything else is a gap that we can fill with whatever you whats.
> 
> I simple question, someone imagine how the AI can paky with this balls and their electrons in a productive way as a child game?

Particles want to get the less energetic possible. One solution (simplifying a lot) it's to use particle swarm optimization to cauculate the local minimum for the potential energy of each particule and check all particle configurations. The problem with this solution is the complexity O(particules*number_of_possible_orbitals) that can be huge. Probally the IA will have to cut some branchs in this scope and get some common patterns. Trying to validade and make less "ifs" and checks, so it reduce the avarage complexity and the time of execution.
