### ISSUE TITLE
Atoms + A.I.

### ISSUE THREAD

**Issue by gabrielt-prathivys** [open-source-ideas/open-source-ideas#226]
After some previous conversation we closed : https://github.com/open-source-ideas/open-source-ideas/issues/214
Lets start:

https://github.com/gabrielt-prathivys/Atoms-AI

## Project description

Create a  interface where the A.I. can solve puzzles and games using atoms.

## Relevant Technology
C++, JAVA, PYTHON

### Complexity

- [X] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)
- [X] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories
- [X] IoT
- [X] AI/ML
- [X] Futuristic Tech/Something Unique

------------------------------------------------------------
Discussion from previous thread as you asked:

Hello everybody.
I'm starting with programming, I've worked with art, design and health. Well, I said that because I can have a very different point of view, and some (many) ideas, but can't execute.

I've seen a lot of papers about AI:
Until now no one has created a neural network, or game, where the lego pieces are the elements of the periodic table. Reaction and responses? Linus Pauling electron interactions: actually every combination of electronic layers is already catalogued.

I just can imagine; scenarios: like a drop of acid in a piece of metal (right corrosive intensity, right alloy properties) trying to pass through. Let the AI try to stop it. If it passes through the process, it restarts in a new generation.

Let's leave the AI learning to use every element, simple mixtures to atomic fusion, quarks in the future maybe? strange matter...well, we already know how to get to the nucleus of a neutron star where came from every dense material.

That is very far away, but if we get to the carbon - enzymes - molecules of diseases or alloys with graphene we already can create and solve some things.

Apologies for the accent, I'm Brazilian. With so many ideas, this is just a test.

Let's the game begins, I hope who see this send to more people and viralize the idea.

Thanks a lot, and Cheers.
![](https://user-images.githubusercontent.com/57564460/70674759-bdcfac80-1c65-11ea-84a4-9ba605b03066.png)

![](https://user-images.githubusercontent.com/57564460/70674751-b8726200-1c65-11ea-8b6e-05d875605330.png)

------------------------------------------------------------

Edited wording and grammar by @FredrikAugust.

**Comment by gabrielt-prathivys** [comment]
https://github.com/gabrielt-prathivys/Atoms-A.I./issues/1#issue-571447455

 [ ] #1 - Cut out existing complex codes, to create the simplest possible interaction of 3-5 kinds of atoms, in a interface that the A.I. can try to solve simple puzzles and get a score.

 Show to the A.I. that we want water, and a box with Hydrogen, Oxygen and some tools (yeah, let's simplify and get easy in the beginning)
EXABYTE - Data about chemical elements arranged in JSON format.
https://github.com/Exabyte-io/periodic-table.js

EXABYTE - JSON schemas and examples representing structural data, characteristic properties, modeling workflows and related data about materials
https://github.com/Exabyte-io/esse

EXABYTE - Design Materials from atoms up - https://exabyte.io/
https://github.com/exabyte-io/

PYSCF - Python Module do Quantum Chemistry
https://github.com/pyscf/pyscf

PYQUANTE2 - Another Python Module do Quantum Chemistry
https://github.com/rpmuller/pyquante2

@losnol suggestion:
Particles want to get the less energetic possible. One solution (simplifying a lot) it's to use particle swarm optimization to cauculate the local minimum for the potential energy of each particule and check all particle configurations. The problem with this solution is the complexity O(particules*number_of_possible_orbitals) that can be huge. Probably the AI will have to cut some branchs in this scope and get some common patterns. Trying to validade and make less "ifs" and checks, so it reduce the avarage complexity and the time of execution.

**Comment by gabrielt-prathivys** [comment]
@FredrikAugust 
@MarchWorks
@KOLANICH
Same issue, better manners, we count on your opinions.

**Comment by KOLANICH** [comment]
Why to flood with issues instead of editing existing ones?

**Comment by FredrikAugust** [comment]
I must agree with @KOLANICH here. Please refrain from recreating issues;

1. I have to re-add labels
2. We lose the previous conversation (which I didn't really see any issues with)
3. People who followed the previous issue will have to find this to continue following the development of the project

Furthermore, there didn't seem to be any bad manners in the previous thread. People were critical to your idea, which is understandable, as this is a very complicated topic, and will require a lot of knowledge and time in order to create something unique. 

I believe it would be beneficial if you let the initiative maintainers determine what is detrimental behaviour and what isn't -- it's easier for us to see it from an objective view compared to you who have already invested time and effort.

Could you also add some more information as to what the project actually is about?

This;

> Create a[n] interface where the A.I. can solve puzzles and games using atoms.

isn't very informative without having read the previous thread. If you just copy over the information from the previous thread, that's fine.

Finally, why is this tagged IoT?

**Comment by gabrielt-prathivys** [comment]
> I must agree with @KOLANICH here. Please refrain from recreating issues;
> 
> 1. I have to re-add labels
> 2. We lose the previous conversation (which I didn't really see any issues with)
> 3. People who followed the previous issue will have to find this to continue following the development of the project
> 
> Furthermore, there didn't seem to be any bad manners in the previous thread. People were critical to your idea, which is understandable, as this is a very complicated topic, and will require a lot of knowledge and time in order to create something unique.
> 
> I believe it would be beneficial if you let the initiative maintainers determine what is detrimental behaviour and what isn't -- it's easier for us to see it from an objective view compared to you who have already invested time and effort.
> 
> Could you also add some more information as to what the project actually is about?
> 
> This;
> 
> > Create a[n] interface where the A.I. can solve puzzles and games using atoms.
> 
> isn't very informative without having read the previous thread. If you just copy over the information from the previous thread, that's fine.
> 
> Finally, why is this tagged IoT?

Hi There, after some conversation with our firts developer interested in the project (Losnol), i think a fresh star with less speculation and more milestone could be better accepted by the community.
I believe people don´t understand what is the idea, and I tried to be more accertive closing the Issue and starting this one.
 I´m new here, i´m sorry.
** I´v tagged as IoT because of others ideas that will came from the system of structuring atoms to solve Puzzles (molecules of diseases), i trully believe that we can create networks with eletrons (my dream) i know its too far...

Cheers!
