### ISSUE TITLE
Demokratix project: a collective intelligence platform based on Laravel 

### ISSUE THREAD

**Issue by michelanthony13** [open-source-ideas/open-source-ideas#233]
## Project description
In a world where Democracy and pluralism are under assault, I firmly believe that its time for us (citizens) to stand up and bring our leaders back to the base. According to the recent report from the Economist Intelligence Unit (EIU, FT1), there are only 22 countries that foll under the Full democracies  category within the Democracy Index.
Knowing all that, I want to develop a suite of participative, civic and OpenSource tools integrated into a single Laravel self hosted Web app that will allow organizations and individuals to manage consultations of all kinds online. Box ideas, information portal and participatory budgets are some examples of the countless possibilities that this platform will be able to offer.
Inspired by "Decidim" and "Cap collectif", this initiative will not only allow stakeholders to have a space where to conduct consultations, but it'll also contribute to promoting citizen participation around the world.
we could even think of internationalizing the software. That's why this project will need a solid and serious team.
I'm aware that such initiatives already exist but they aren't complete  and are hard to install.
I'm already working on the communities Website.
### Linear Organizational chart of the basic components
Participatory spaces may include:
``
<ul>
<li>Consultations</li>
<li>Decision groups</li>
<li>Assemblies</li>
</ul>
The above would then be subdivided into components:
<ul>
<li>Meetings: can be used into assemblies and decision groups</li>
<li>Debates: can be used in discussion groups and assemblies</li>
<li>Comments: can be used in all of the above</li>
</ul>
``
More components / extensions could then be added via a repository.

## Relevant Technology
* Php 7
* Laravel framework
* Html-5
* CSS

### Complexity
- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [X] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)
- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [X] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories
- [ ] Mobile app
- [ ] IoT
- [X] Web app
- [X] Frontend/UI
- [X] AI/ML
- [X] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [X] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique
Footnote #1: The EIU is a UK-based company that measures the state of democracy in 167 countries every 2 years.

**Comment by aakashsinghbais** [comment]
@michelanthony13 , why did you close it? It was a nice project.
