### ISSUE TITLE
Browser extension to capture full-page screenshots in all screen sizes

### ISSUE THREAD

**Issue by AdrienDS** [open-source-ideas/open-source-ideas#234]
## Project description

[Chrome Developer Tools](https://developers.google.com/web/tools/chrome-devtools/device-mode#responsive) and [Firefox Developer Tools](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode#Using_Responsive_Design_Mode) both have a mode to simulate multiple device sizes. And both have an option to take either a full-page screenshot or a screenshot of the visible area of the page.

But none have an option to capture one screenshot per screen size / media query / device with a single click.

It would be useful to have an extension that would either:
- Capture one screenshot per media query breakpoints
- Capture one screenshot per width in a set (or customizable) list 
- Capture one screenshot per device in a set (or customizable) list 

It would be nice if, prior to starting the screenshot series, the extension could present a modal with a few options:
- Text box, filled by default with the date, to set a name for the layout (the name of the file would then be `{layoutName}-{size}`
- Full size? check-box to toggle between capturing only the visible area or the full page
- Sizes selector to select which sizes/devices/breakpoints to capture

## Relevant Technology
Javascript, Browser extensions

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [x] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [x] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [x] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [x] Developer Tooling
- [x] Extension/Plugin/Add-On
- [x] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by lipfreitas** [comment]
You can open Google Chrome Inspector
Press CTRL+SHIFT+P
Type Capture and select one of the options:
![image](https://user-images.githubusercontent.com/21109081/81510152-145d1780-92e6-11ea-857e-a93b42f9855a.png)

**Comment by HamzaEzzRa** [comment]
I've been working on something similar these past few days.
It's still far from perfect, so any help would be very welcome: [https://github.com/HamzaEzzRa/Multishot](https://github.com/HamzaEzzRa/Multishot).

**Comment by virtadpt** [comment]
I suggest naming it "Keep Your Receipts."

**Comment by AdrienDS** [comment]
Fantastic ! That's exactly what I was looking for. 

I'll be watching this repo, thank you for sharing it!

If I could suggest to add an option in the settings to add a delay in seconds before the capture (default=0). Some pages continue to render some elements after the page is loaded, so we might want to wait let's say 5 seconds before taking the screenshot. 

Another useful option could be to render the page with a zoom (80%, 120%), that could be a way to capture a screen size larger than the physical screen that the screenshot is captured on.

**Comment by HamzaEzzRa** [comment]
Thank you for the suggestions @AdrienDS !

They seem to be excellent ideas, considering I'll be working on the options page next. If you've got the time, feel free to open the issues for them.

**Comment by FredrikAugust** [comment]
Great collaboration! Let me know if you feel this issue is completed, and I'll add it to the hall of fame!

**Comment by AdrienDS** [comment]
@FredrikAugust the extension does exactly what I had in mind. I would just check with @HamzaEzzRa  if he plans to publish the extension to the Chrome Web Store, and if he wants to do that before the publication in the hall of Fame.

**Comment by HamzaEzzRa** [comment]
Thank you, @FredrikAugust. I'll be honored for the extension to be listed in the hall of fame. I'm currently pushing for an official release to the Chrome Store, however the submission may take some time, so feel free to add the extension any time.

**Comment by FredrikAugust** [comment]
I'll do it now!:) Good work @HamzaEzzRa! :100:

**Comment by FredrikAugust** [comment]
Done!
