### ISSUE TITLE
Bump version of files mapped on a root project file

### ISSUE THREAD

**Issue by brunowego** [open-source-ideas/open-source-ideas#239]
## Project description

A simple software, when running, update version of files that are mapped in a `.bumped` file. Any extension are supported.

Example of `.bumped` file:

```yaml
version: 0.1.0
bumps:
 - file: /path/to/first-file
 - file: /path/to/second-file
```

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [x] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [x] Little work - A couple of days
- [ ] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [x] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by TheOtterlord** [comment]
So I imagine the program would look for something that matches a semantic versioning pattern and replace it with the new version number?

**Comment by brunowego** [comment]
Exactly!

**Comment by TheOtterlord** [comment]
Cool. I'll give it a go 😄

**Comment by KOLANICH** [comment]
https://github.com/peritus/bumpversion

**Comment by TheOtterlord** [comment]
@KOLANICH while this looks good, it does not seem very active and there are a lot of issues. Also the build seems to be failing.

**Comment by KOLANICH** [comment]
@TheOtterlord, I personally don't use this tool. Instead I use `setuptools_scm` - the tool fetching versions from git tags.

**Comment by TheOtterlord** [comment]
@brunowego I've completed a working program created with Go. I still need to add documentation, but it basically follows the schema above. I also have not created a release yet as I don't know how to create an installer for a command line tool. If anyone here happens to know how, any help is appreciated. I'm going to do some research soon, but for now you can build it using `go build`.

Let me know what you think :-)

**Comment by TheOtterlord** [comment]
@brunowego I've updated my repository with better documentation and cleaned up the code. I've also added an installation method. You'll need [Go](https://golang.org) installed, but once you do, you only need to run one command.

```bash
go get github.com/TheOtterlord/SemanticBumper
```

Then you can run the command using `SemanticBumper` appended by your `.bumped` file. Head over to the [repository](https://github.com/TheOtterlord/SemanticBumper) for more details.

**Comment by TheOtterlord** [comment]
@brunowego I think I have implemented everything that it needs, but I will be adding to this over time. I just added a method to [update](https://github.com/TheOtterlord/SemanticBumper#update) the software so that you can take advantage of any new additions. 

I think I've implemented everything you mentioned in your issue, but if you think I've missed anything or have any ideas to improve it, feel free to let me know here or open an issue on the [repo](https://github.com/TheOtterlord/SemanticBumper).

**Comment by brunowego** [comment]
Yeah! Thanks a lot for this. Exactly I'm looking for. Great work!
