### ISSUE TITLE
Sharing Modded APKs

### ISSUE THREAD

**Issue by GrpeApple** [open-source-ideas/open-source-ideas#252]
## Project description
Share Modded APKs to people.
I don’t know if it is illegal and I don’t know where to start.
I am not going to support the project.
[Github repository](https://github.com/GrpeApple/ModAPKs)

## Relevant Technology
Android, Java, and ?

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [x] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [x] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [x] Mobile app
- [ ] IoT
- [x] Web app
- [x] Frontend/UI
- [ ] AI/ML
- [x] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by KOLANICH** [comment]
1. An XPosed module may  be much better than a modded APK for some cases.
2. There exists a software for applying binary patches onto installed apks bytecode. It contains large quantity of binary patches within itself.

**Comment by KaKi87** [comment]
> A place for you to share, copy, modify, distribute mods for Android ( or can install APKs ).

Aptoide.

> An XPosed module may be much better

It requires root.

> There exists a software for applying binary patches onto installed apks bytecode. It contains large quantity of binary patches within itself. Mostly removing ads.

Lucky Patcher, which also requires root.

**Comment by GrpeApple** [comment]
@KaKi87 
> Lucky Patcher, which also requires root.

Lucky patcher can work without root, by modifying the apk.
Can see, why my idea is bad. Thus validating that I will not support this.

**Comment by KaKi87** [comment]
Well, whoever wants to build modded APKs either publish on their own on a repo (when open source) or on a website (when proprietary), or join a team that already has a publishing platform.

So, if you just want to create modded APKs, you can just create your own repo, and if you want to create a centralization project, you can go for an [https://github.com/sindresorhus/awesome](https://github.com/sindresorhus/awesome) list.

**Comment by GrpeApple** [comment]
I am tired of this. I will reopen it when something changes.
