### ISSUE TITLE
drop down clipboard manager when pressind and holding Ctrl + v

### ISSUE THREAD

**Issue by KlimaRitter** [open-source-ideas/open-source-ideas#259]
## Project description

A small program, that, if you paste something using Ctrl + v, when holding down shows a drop down list of prior elements in your clipboard you can navigate trough with your arrow keys and simply paste with enter.

**Comment by KaKi87** [comment]
1. You didn't followed the template
2. You can use any existing clipboard manager app (e.g. : CopyQ) and assign it this shortcut

**Comment by KlimaRitter** [comment]
I am sorry I didn't follow the template, but I had no idea how to answer most of the questions.

**Comment by FredrikAugust** [comment]
I'm sorry, but at least _try_ to provide some insight into your idea. I'll reopen the issue if you fix it, but I'd suggest making a new one instead.
