### ISSUE TITLE
The Shadow App

### ISSUE THREAD

**Issue by MarkoArmando** [open-source-ideas/open-source-ideas#263]
This is an idea that I have been gifted with and I am giving it to creation out of love.

https://www.youtube.com/watch?v=xmtlLJBOT-g

https://www.youtube.com/watch?v=29cjQ9yJirU&t=9s

Take care and good luck!

**Comment by KOLANICH** [comment]
@MarkoArmando, please fill in the template. And please remember that issues that don't follow the template are not very welcome here. Especially the ones described as videos on YouTube - a proprietary privacy-abusing videohosting.

**Comment by MarkoArmando** [comment]
> @MarkoArmando, please fill in the template. And please remember that issues that don't follow the template are not very welcome here. Especially the ones described as videos on YouTube - a proprietary privacy-violating videohosting.

Hello, where can I find this template? If I have violated any rules, I apologise and will remove the content.

**Comment by TheOtterlord** [comment]
@MarkoArmando When you create an issue in the repository, you should see the template already there.

**Comment by FredrikAugust** [comment]
Thank you for your contribution, but as mentioned by @KOLANICH we would very much appreciate if you could use the provided template.

I will close this issue, and hope you will submit another one according to the template.
