### ISSUE TITLE
A cli tool to stand up a static website in a couple commands

### ISSUE THREAD

**Issue by roymoran** [open-source-ideas/open-source-ideas#271]
## Project description

A tool that helps stand up a static site in just a couple commands using any registrar/host of your choice. I'm not sure it solves a major problem - but it would be useful to have a small utility that makes deploying a static site quickly pretty straightforward. Mucking around with DNS records and manually registering an ssl certificate for a custom domain become menial tasks that I think can be automated away.

The cli interface would go something like this. A 'page init' command to create a new project which generates a .yml definition file and 'page up' to create the site based on the details provided in the definition file. 

```bash
$ page init
$ page up
```

Here's what the definition file would look like. 
```yaml
host: "aws"
registrar: "namecheap"
domain: "example.com"
template: "url to static assets"
```

It should also support configuring your registrar/host of choice so the tool could support multiple hosts like aws, azure, gcp or even github pages. And multiple registrars like namecheap, godaddy, cloudflare. 

I imagine the tool would mainly be useful for deploying things like a landing page, product launch page, sales page, or event page. Sites that might be short lived and don't require any changes after deploying. This wouldn't be used as a day to day developer tool for developing applications.

## Relevant Technology

go, terraform
### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [x] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [x] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by tuatara73** [comment]
Should it be cross platform?

**Comment by roymoran** [comment]
@tuatara73 i ended up hacking something together for this project and open sourced it. https://github.com/roymoran/page

I created an initial release for windows, linux, and macos. It's still alpha version. May add additional hosts/registrars in the future.

**Comment by FredrikAugust** [comment]
Cool! Would you say the issue is complete, @roymoran?

**Comment by roymoran** [comment]
yeah I would say so. I'll go ahead and close it. I'll create a PR to update the readme with this completed project. Maybe others will find it useful or just want to contribute to it in the future.

**Comment by FredrikAugust** [comment]
Great work!

**Comment by fire17** [comment]
Please add command to re-ssl 🙏
Seems as after 90 days the certificate is outdated.
Would like a command that does this whenever I choose or every given time so it will be automated. Thanks a lot 😊👍

**Comment by roymoran** [comment]
@fire17 yep totally agree. it's been on the [todo.txt](https://github.com/roymoran/page/blob/main/src/todo.txt). I've just been focused on a different project for the last months so I won't be adding this right now. I'll let you know when I do add it.

**Comment by fire17** [comment]
Thx :)
noticed that pagecli.com certificate is outdated so I wrote..

**Comment by roymoran** [comment]
Hey @fire17 its only took me a couple years but I added certificate renewal to the new release. Run `page up` on a previously deployed page and it will check the certificate for renewal. When it's within 30 days of expiry it will update the certificate. 

Installation is also more straightforward:

```bash
# for macos/linux
$ curl -sSL https://raw.githubusercontent.com/roymoran/page/main/install/install.sh | sh
# for windows powershell
$ Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/roymoran/page/main/install/install.ps1')
```

Please keep in mind this is still an early version so expect breakage between releases while it remains in alpha.

I've decided to sell this tool. The open source version will continue to work great for personal use. If you're interested in this tool for commercial use (profit-generating activities) please download the commercial version from [pagecli.com](https://pagecli.com). Thank you.

**Comment by fire17** [comment]
@roymoran Hey man, thats actually pretty awesome!
Happy you made it work! & good luck with pagecli ! happy you still keep some of it open source

if you can please include older macs with intel (im currently on an old mac air bigsur i got from a friend)
hope to re-test it soon :)
All the best!

**Comment by roymoran** [comment]
@fire17 Thanks. For macOS installation I have created a .pkg installer. So terminal installation is not needed. 

Take a look at the latest [release](https://github.com/roymoran/page/releases) and download the .pkg for intel based Mac. Reach out with any complaints and I'll fix. Still not perfect but work in progress.
