### ISSUE TITLE
Github bot that automatically adds labels according to issue contents

### ISSUE THREAD

**Issue by Kreijstal** [open-source-ideas/open-source-ideas#282]
## Project description

For example using checkboxes, the bot would understand the desired categories, and label the issue accordingly
## Relevant Technology

Probably work with Github API
### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [x] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [x] Little work - A couple of days
- [ ] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [x] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by KOLANICH** [comment]
Already implemented. For a long time. By me. For this org ;) But not used - noone wants to be ready to fix it (and if it is not fixed when broken, it will shit into email with broken pipeline notifications, since it is started every 5 minutes, and it can very easily go broken - it happenned a couple of times already).

**Comment by KOLANICH** [comment]
And it is not "little work".

**Comment by Kreijstal** [comment]
well then

**Comment by FredrikAugust** [comment]
Yeah, as @KOLANICH pointed out; as the lone maintainer of this project I don't want to have the responsibility of setting it up and making sure it works/fixing it. I offered him to set it up himself, but as he was not comfortable with that responsibility; it was put on ice.

There are also a surprising amount of people who break the checkbox system, so I think the level of manual overhead required would make it obsolete.

Examples of broken checkboxes I've found
- `- [ x]`
- People remove the ones not used
- People add extra information to the checkbox entries
- People don't check any boxes
- People say "this doesn't fit into any categories" and remove it all

**Comment by FredrikAugust** [comment]
If you have any ideas on how to improve the community, I'm all ears! We also have a repository for this over at https://github.com/open-source-ideas/meta

**Comment by Artturin** [comment]
> > People remove the ones not used
> 
> My bot is OK with it (the schema is taken not from the issue itself, but from its template) and it is even meant to have a feature to enforce removal of unneeded checkboxes.
> 
> > People don't check any boxes
> 
> The bot validates the requirements and closes issues if they are not fixed within a certain interval after the warning (can also be moved into a separate repo, but deletion of issues is not implemented because this GH API is not documented). Also banning persons is implemented in the lib used for GH API (I have created an own lib, with the goal to have it small), but I have not decided how to keep a DB of nicknames with counts of template violations.

Hi, is the source code available anywhere?

**Comment by FredrikAugust** [comment]
If you would like to take a look at the issue @Artturin, you'd be more than welcome to! You could also take a look at the new form-based issues by Github. I think they would be a great fit!

**Comment by KOLANICH** [comment]
>And just after making this comment I found it https://github.com/KOLANICH-GHActions/issuer

I have not checked if it works since I understood noone uses it and disabled it in the test repo. It is very likely that it got broken.

>take a look at the new form-based issues by Github. I think they would be a great fit!

Yeah, but their support is needed, but is not yet implemented.
