### ISSUE TITLE
Transform this repo into an organization and setup teams and permissions

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/open-source-ideas#56]
This should allow to [setup permissions more granularly](https://help.github.com/articles/creating-a-team/). For example for now I have write access to this repo (thank you for the invitation, BTW). But I'm not sure in the security of the devices I use, if someone had hacked my device (which is pretty easy), he would be able to do nasty things from my account. So, I think more granular permissions are needed as a security measure.

**Comment by mikaelbr** [comment]
Fixed 👍

**Comment by KOLANICH** [comment]
I'm sorry for misinformation, but it seems there is no granular permissions for orgs (I was sure it was). So I exit the org, feel free to add me again when GH adds the needed permissions (I needed only labels creation and assignment) and you setup them. Thank you anyway.
