### ISSUE TITLE
NPM dependency helper based on semver

### ISSUE THREAD

**Issue by Epikem** [open-source-ideas/open-source-ideas#65]
## Project description

[This site](https://semver.npmjs.com/) shows node package versions with semver filter. I think it would be useful if this could be done with multiple packages with pivot package's semver based filter. And it would be also better if anyone could comment what is changed on each versions.

## Relevant Technology

node, javascript, npm

## Who is this for

node community

---

**Comment by FredrikAugust** [comment]
Please provide a bit more thorough explanation of the project. This is _very_ vague.

**Comment by cloudson** [comment]
Agree with FredrikAugust. There is another site with similar proposal https://david-dm.org/request/request .

**Comment by Epikem** [comment]
Sorry for vagueness. What I wanted was that if I set filter of A and B package, and I upload package.json then it will show lastest possible all the dependency graphs with A and B's all dependencies not changed. However, I didn't know what peerdenpencies does and I think it is not useful now. Maybe migration guide by comments would be useful but that could be done without dependency graphs etc.
