### ISSUE TITLE
Have issue/project creators suggest labels regarding difficulty themselves

### ISSUE THREAD

**Issue by FredrikAugust** [open-source-ideas/open-source-ideas#71]
Hey,

So as of now, I'm basically the only one updating the labels on the issues here, and since I don't really know much about 70% of the projects being suggested here, the quality of my suggestions are rather bad.

So, I'm proposing an update to the template where the creator is asked to fill in what he thinks should be the labels.

Please comment with your thoughts.

Thanks,
Fredrik

**Comment by mikaelbr** [comment]
Sounds good to me. This was the plan all along also. For the issuers them self to estimate ballpark. The idea it self isn't for an accurate estimation of time used, but just to get an initial sense of the scope and complexity the original issuer imagines.

**Comment by KOLANICH** [comment]
The problem with this idea that the labels should be chosen from existing subset and reused, otherwise there is no sense to have labels. Not sure if it is possible to grant strangers privilege to create and assign labels. Should we use StackExchange?

**Comment by mikaelbr** [comment]
I don't think this is much of a problem per se, as there are humans adding them as actual labels?

**Comment by KOLANICH** [comment]
Or maybe just add into the template a section for proposed labels, and a participant with privilege (may be a bot) will create them for a user if the label is reused in any other issue.

**Comment by FredrikAugust** [comment]
That was exactly what I was thinking. I'll see if I can't get around to making said bot, shouldn't be that hard. But for the time being, just make them tick off the labels they think is fitting and I (or @mikaelbr) can update them manually.
