### ISSUE TITLE
National Weather Service (USA) android app

### ISSUE THREAD

**Issue by xenotropic** [open-source-ideas/open-source-ideas#74]
## Project description

 Right now the only open source app that pulls NWS data only shows alerts, hasn't been updated in six years, and it doesn't seem to work on my phone (does not appear in list of widgets) .

 https://github.com/justdave/nwsweatheralertswidget

 The app  I am proposing would pull data from the NWS API , and display it somehow on an android phone. Even just displaying textual data for the users location (or user-submitted location) would be a contribution. More advanced would be to integrate icons, and more advanced displays. I think there is even radar data that can be displayed, but that would be even more advanced. Ideally would show current conditions as well as forecast. 

https://www.weather.gov/documentation/services-web-api

## Relevant Technology

this would be a good project for someone looking to get familiar with APIs, and contribute something new to that world. The NWS API appears to be a pretty typical JSON data source for which there are certainly existing parsers.

## Who is this for

This is probably a mid range difficulty project, suitable for a student that has made one or two simple applications and wants to learn more about data handling and processing, particularly API/JSON data sources.

**Comment by FredrikAugust** [comment]
You could also create a web app if you wanna make this a bit easier. That way it would be really easy for someone new to programming to work on this. But that's just a suggestion ;) Cool project!

**Comment by GriffinAustin** [comment]
Like this idea; will update when I have time to start planning.

**Comment by ppeters0502** [comment]
This sounds interesting! I've done some android work before, and have worked in a team environment with source control, but I admit I'm new to contributing to an open source project. Would love to partner up with you guys on this if you're open?

**Comment by FredrikAugust** [comment]
Sounds good, two people on board!

**Comment by saiteja09** [comment]
Sounds cool, interested in collaborating with you guys to build the app. I have done a bit of android development in the past, but like @ppeters0502 I'm also a bit new to open source projects.

**Comment by ppeters0502** [comment]
@FredrikAugust, if you already have a slack server set up, I'd love access!! From there we can figure out who wants to start where, what the app requirements should be, and get the ball rolling!

**Comment by sikrinick** [comment]
I am an Android developer, so if there any design or, at least, some chat to talk about, I would be glad to.

**Comment by FredrikAugust** [comment]
Wonderful, there should be a badge in the Readme that takes you to it :))

**Comment by FredrikAugust** [comment]
I'll set up a channel for you now

**Comment by FredrikAugust** [comment]
#nws-app is up and ready for use :)

**Comment by Pheonix73** [comment]
I will love to be part of this project, how can i start??

**Comment by FredrikAugust** [comment]
Wonderful @Pheonix73! Just join the Slack group found in the README and I'll guide you through it! Someone already begun working, but I think it stagnated :)

**Comment by PraneethVankayala** [comment]
I am learning the android in udacity and side by side i am doing the apps and when i read about the project i have the confidence that i can do and it may help to learn more about json parsing.I am new to the opensource

**Comment by PraneethVankayala** [comment]
please join me in your group so that i can contribute from my side

**Comment by ppeters0502** [comment]
Sounds good @PraneethVankayala! If you check the readme, theres a link to the slack server @FredrikAugust created and we can connect on the nws channel!

**Comment by Areahints** [comment]
hello, im really intrested in learning about APIs and how they work! any space for a lurker/infrequent contributor like me, i dont know how much i can contribute, but i want to learn :)

**Comment by ppeters0502** [comment]
Hey @Areahints! In the readme on the open-source-ideas project, there's a link for the slack server that @FredrikAugust created for the open-source-ideas project. Once you get there, there's an nws-channel that we've been using for chatting about the project!
I try to hop on there a couple of times a week to talk about the project, but we've had a bit of a slow start. Feel free to hop in!

**Comment by PraneethVankayala** [comment]
Thank you sir

**Comment by PraneethVankayala** [comment]
@ppeters0502 can you please send me the link to the slack server, due to the poor internet connection in my house for 4 days I am not able to search the link, please send me the link sir

**Comment by Areahints** [comment]
@praneethvankayala  i use a poor network too, so i understand your pain

https://opensourceideas.herokuapp.com

**Comment by azz-eddine** [comment]
Hello all,

@xenotropic i like your idea, here is my take based on your idea and the suggestion of @FredrikAugust to do it as a web app.

The repo is here :
https://github.com/azz-eddine/nws_webapp

The live version :
http://nws.overnightproject.com

Best regards,

**Comment by xenotropic** [comment]
@azz-eddine I love it! I think I actually will use this on a regular basis, because I'm just tired of waiting for bloated weather websites to load. Super-gratifying to have my "hey wouldn't this be neat" thought turn into to live app. 

After a quick test drive, I have a bug and a feature request (it's not really software until it has a bug and a feature request!). I'll put those as issues in your repo.

**Comment by azz-eddine** [comment]
@xenotropic Thank you for you replay. 
I'll be delighted to fix the bug and implement the feature :)

**Comment by xenotropic** [comment]
@azz-eddine Great! Gave you a few open issues. Don't feel obligated of course. Being open source, I can always fork and make changes if they aren't stuff you want to do.

**Comment by xenotropic** [comment]
@FredrikAugust this one can be closed as complete, credit to @azz-eddine - just realized that this hasn't been done since you closed the other one I suggested.

http://nws.overnightproject.com is one of the main ways I get weather info now!

**Comment by FredrikAugust** [comment]
Done! Great job @azz-eddine!
