### ISSUE TITLE
Twitter bot for Open Source Ideas

### ISSUE THREAD

**Issue by mikaelbr** [open-source-ideas/open-source-ideas#80]
## Project description

It might be difficult to track new projects being posted in this repository. One way this could be improved is by having all new issues in this repo be tweeted to a Twitter account.

There might be some existing technologies for this that I'm not aware of, but my small initial research didn't uncover anything. Please let me know if you know of any.

## Relevant Technology

- Github API and probably some hooks
- Twitter API
- Some hosting solution (probably PaaS/FaaS would do.)
- Language/platform of your choice.

## Who is this for

This is a small project suitable for anyone wanting to explore the Github and Twitter APIs.

**Comment by FredrikAugust** [comment]
Good idea! 💡

**Comment by Peter42** [comment]
https://ifttt.com/ should be sufficient

**Comment by FredrikAugust** [comment]
Good idea, but not nearly as fun ;)

Btw, is ifttt OSS?

**Comment by mikaelbr** [comment]
@Peter42 Good point. Though, maybe IFTTT isn't the best if we want shared ownership/maintainability. Maybe this is so simple we don't need that.

**Comment by ehamamrah** [comment]
I don't see moving to Twitter as a good idea, Github is better. At least, people can have a look at the repository after years. 
I would recommend working on a platform to publish the new ideas in collaborating with this GitHub repo.

**Comment by mikaelbr** [comment]
@darshkpatel I guess you could use something like Zeits Now for free.

**Comment by remram44** [comment]
You might be able to abuse CI to do this, e.g. set up Travis/GitLab/... to run a task every day at 10am, and go over the issues and tweet them at that time.

The code for it (and CI configuration) do not need to be in this repo, and could be in `open-source-ideas/twitter-bot` or similar.

**Comment by mikaelbr** [comment]
I think using [Webhooks](https://developer.github.com/v3/activity/events/types/#issuesevent/) and a tiny API layer on Now (given that it's Node.js) is less work, more flexible, and allows for continuous tweets instead of periodic updates. The API layer needs one HTTP POST handler, create tweet text from the issue title and post a tweet. If one want, this could also extend to work on different repos as a generic service.

**Comment by remram44** [comment]
You probably don't want "continuous tweets" (by which you mean "instant"). To maximize visibility, there are specific times where it is better to send them out. Just a thought 😉

**Comment by KOLANICH** [comment]
>To maximize visibility, there are specific times where it is better to send them out. 

Could you clarify, why?

**Comment by remram44** [comment]
Happy to! There are known times when people check their Twitter (around noon). If you tweet when your target audience is asleep, or busy, you are unlikely to reach many people. This is also dependent on the timezones of your audience. That's why tweet-scheduling apps are very popular (Buffer, etc).

The Rust team was recently considering posting each message twice, to reach people in both US and EU timezones (Mozilla is pretty spread out): https://users.rust-lang.org/t/tweets-and-timezones/16310

**Comment by testman42** [comment]
Should also make it to work with Diaspora* or even other FOSS social networks and communication platforms.

**Comment by FredrikAugust** [comment]
Perhaps a silly question, but how do I join for diaspora*? Couldn't find any information on that on the website. 

I think starting with Twitter should be enough, and then rather expand to other services later, as Twitter presumably has a lot larger audience.

**Comment by KOLANICH** [comment]
>how do I join for diaspora*? 

I guess https://wiki.diasporafoundation.org/Installation

**Comment by azz-eddine** [comment]
Hello @mikaelbr 

I like this idea and tried to implement it here :
https://github.com/azz-eddine/open-source-ideas-twitter-bot
Should i install a live version of it so it can be tested ? 

It's a work in progress.. for now the application can tweet the title and the link of the 'issue' of it's created or updated.
I plan to also implement the tweet scheduling idea described by @remram44 

Your feedback is welcome.

Thanks

**Comment by mikaelbr** [comment]
Very cool! If you want we can transfer the repo to this org for easier maintenance and visibility. Or you could just keep it with you if you prefer that. Anyways, I think we can go live already and improve incrementally. 👍

**Comment by azz-eddine** [comment]
Yes sure ! you can transfer it yes :)

**Comment by FredrikAugust** [comment]
Quick question @azz-eddine; how does it handle too long titles?

And, is it necessary to post updates? I quite frequently hop into issues and fix typos and clean up formatting, so I think the bot would post a lot more than necessary.

But great work! :)

**Comment by FredrikAugust** [comment]
If you transfer it now, I'll create a group of people who can edit it, and add you to it @azz-eddine :)

**Comment by FredrikAugust** [comment]
Sorry, forgot to mention, you have to transfer the repository yourself @azz-eddine; there should be a button under the settings page of the repo where it says "Transfer ownership", and you can enter the org name there! :+1:

**Comment by azz-eddine** [comment]
@FredrikAugust i tried to transfer it to open-source-ideas but it tell's me that i don't have the permission to create repositories on open-source-ideas.

**Comment by FredrikAugust** [comment]
@azz-eddine Strange, if you're comfortable with it, you could transfer it to me, and then I'll transfer it to this organization, and then add you as a contributor to it.

**Comment by azz-eddine** [comment]
@FredrikAugust of course, but : FredrikAugust/open-source-ideas-twitter-bot already exists

**Comment by FredrikAugust** [comment]
Oh, right, silly me, one second @azz-eddine.

**Comment by azz-eddine** [comment]
Done :) thanks @FredrikAugust for your help

**Comment by FredrikAugust** [comment]
No problem!

**Comment by FredrikAugust** [comment]
https://github.com/open-source-ideas/open-source-ideas-twitter-bot -- Done!

**Comment by FredrikAugust** [comment]
@karuppiah7890 I don't think it's setup yet, I'll get @mikaelbr take care of that :)

**Comment by daniel-lacour** [comment]
Made it.

**Comment by daniel-lacour** [comment]
@OpenIdeas3

The first one's are out of order, but continuing ones will be in order.

**Comment by rijkerd** [comment]
Sounds great!! New to open source though

**Comment by mikaelbr** [comment]
It seems many found this interesting and have implemented it. I think there is still high personal value in implementing it and having fun with it, but we'll give @azz-eddine some time to publish the one they implemented and we can use that for now.

Thanks all for all the involvement. Love the energy! 🍰

**Comment by azz-eddine** [comment]
Hello,
Thanks @mikaelbr , actually i have a bit of trouble to deploy on pythonanywhere.com
Can anyone help please ?

**Comment by azz-eddine** [comment]
Hello,

First automated tweet sent :)
https://twitter.com/OS_Ideas

Thanks all

**Comment by remram44** [comment]
Don't want to start bikeshedding, but I think `OSS_Ideas` would be a better name, since "OS" usually means "Operating System" :wink:

**Comment by mikaelbr** [comment]
I get your point, but there’s technically not something limiting this project to software. You could have open source design, hardware, nitting recipes, and so on. In the end, I don’t think people will see the name and think «no, I don’t need any more ideas to my windows me, thank you». I don’t think it matters that much.

**Comment by mikaelbr** [comment]
Considering this as done 🎉

**Comment by fire17** [comment]
Yo yo, will this go back live? Last tweat was over a year ago ... Who was running it ? We're there any technical problems (with the APIs for example) or just a matter of keep up a server ?
Thx :)
