### ISSUE TITLE
Help people to avoid failure, a voting app on people project ideas :)

### ISSUE THREAD

**Issue by ehamamrah** [open-source-ideas/open-source-ideas#83]
## Project description

Every day I'm enjoying products launched and announced through ProductHunt. 
Usually, people are being afraid to start just because of the sense of failure. Here becomes the promised platform. 
A mix of HackerNews & Product Hunt ..
People can share their ideas, others vote for it. just like this! will No :)
Other users can recommend a business model to run the expected project, can give suggestions as well .. a lot to come.

## Relevant Technology

Ruby On Rails, Haml, Sass, Bootstrap

## Who is this for

Everyone, Seriously anyone could join. 

## Complexity and required time

_Please only tick off one box in each category by changing `[ ]` to `[x]`. The labels on the project will then be updated by the maintainers as soon as possible._

### Complexity

- `[ ]` Beginner - This project requires no or little prior knowledge of the technology(y|ies) specified to contribute to the project
- `[x ]` Intermediate - The user should have some prior knowledge of the technology(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- `[ ]` Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- `[ ]` Little work - A couple of days
- `[ ]` Medium work - A week or two
- `[x ]` Much work - The project will take more than a couple of weeks and serious planning is required

---

Share on Twitter/other social media if you will. Something like

```
New project on Open Source Ideas Initiative: [fill in short description] – [fill in link]
```

**Comment by piedoom** [comment]
How would you get users to use the project, instead of this issue repository for example?  What about Reddit, etc.?

**Comment by FredrikAugust** [comment]
Suppose you could use the website as an alternative front-end, where issues created there are created here and vice-versa.

**Comment by ehamamrah** [comment]
@piedoom do you consider Reddit as a valuable product to get people to share ideas and help each other building it? 
Each Social Media Network helps people gathering and discuss, but not focusing in deep for it.

**Comment by ehamamrah** [comment]
@FredrikAugust it could be helpful also :)

**Comment by piedoom** [comment]
I think the biggest hurdle for social media websites is gaining a userbase.  Sites like Reddit (or GitHub) don't have to go through the extra friction of creating an account.

**Comment by ehamamrah** [comment]
piedoom, the main focus is to allow users to share ideas and collaborate on studying all cases to make it live. 
It's not about focusing on GH issues.
 
Best explain: You have a business idea and afraid about it? share it with others and see how people could engage on it and support you by their addition to it.

**Comment by piedoom** [comment]
My apologies, I mean *this* Github Repo Issues section specifically, not issues in general.
