### ISSUE TITLE
Automatic gasoline filling 

### ISSUE THREAD

**Issue by LokeshVarman** [open-source-ideas/open-source-ideas#86]
Need to detect the cash and finding the value of it and releasing the quantity of gasoline for that value

**Comment by FredrikAugust** [comment]
Please follow the template provided to you when creating an idea, and specify your project in greater detail. As of now I have no idea what your idea actually is :disappointed:. Thanks a lot for your suggestion though! I hope you'll resubmit it in a more complete form.
