### ISSUE TITLE
Open Mall - integrating many e-commerce in the world

### ISSUE THREAD

**Issue by prastowoagungwidodo** [open-source-ideas/open-source-ideas#90]
## Project description

Open Mall works as the center of many e-commerce with thousand variety of products to browse. It is integrated with your current e-commerse (e.g. opencart, magento, etc) by installing Open Mall plugins or extensions. Your products which are displayed in your e-commerce will be displayed in Open Mall as well. With Open Mall, we wish to see you promoting your e-commerce in an easier way. Besides, Open Mall is supposed to help customer find their need of products in one click.

### How it works
We will provide plugins or extensions for almost all open sources e-commerce software to communicate with Open Mall API. You just need to register and get credentials to access our API. the plugin/extension simply push your current products to Open Mall Database and place the order (from Open Mall Web) to your current e-commerce. 

User can search many product in Open Mall Web and will directly place order to partner e-commerce without leaving OpenMall Web.

The partner just relax and enjoy their current e-commerce.

## Relevant Technology

Open Mall works like other Marketplace software but it provides API and Plugin / Extension to gather e-commerces. With the latest technology, Open Mall will keep you up-to-date.
It uses javascript (React/Angular/React) as the front-end language.

## Who is this for

Everyone can join this project,  especially web developers, ui/ux designer and other related developers.

## Complexity and required time

_Please only tick off one box in each category by changing `[ ]` to `[x]`. The labels on the project will then be updated by the maintainers as soon as possible._

### Complexity

- `[ ]` Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- `[ x]` Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- `[ ]` Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- `[ ]` Little work - A couple of days
- `[ ]` Medium work - A week or two
- `[ x]` Much work - The project will take more than a couple of weeks and serious planning is required

---

Share on Twitter/other social media if you will. Something like

```
New project on Open Source Ideas Initiative: [fill in short description] – [fill in link]
```

**Comment by FredrikAugust** [comment]
Thank you for your contribution, but I would say it's a bit thin considering the size of this project. Could you elaborate on how you wish to achieve this in greater detail? Perhaps take a look at #78 as well -- lots of similarities in the projects.

**Comment by prastowoagungwidodo** [comment]
because this project is similar to other projects (Nile). you can close this issue. and maybe i can join the Nile Project.

**Comment by KOLANICH** [comment]
icecat.biz?
