### ISSUE TITLE
Docker builder - A way to build a docker image from a container history 

### ISSUE THREAD

**Issue by cloudson** [open-source-ideas/open-source-ideas#91]
## Project description

This project is something that I would like to build but I've failed trying it before. If someone could help me even with a thought it would be very helpful. 
Basically the idea is make possible to user enter a container base, make changes on it (install new tools, create files...) and after that (exiting the container or explicitly running a command like `docker-builder end`) a Dockerfile is going to be built with all the history of the container. 

* Example 
`docker-builder start go/alpine-3.8` 
The command pull the image, up a container and enter inside it. The user run something there andfinish it, building a dockerfile. 

* Problems
The "easier" way could be list all the commands those run with success (bash `$?`) and generate a docker file with the list but I don't know if it's possible. 
Second way is build a whole terminal to track all the errors and successful commands running in parallel in the container. 

## Relevant Technology

Docker and maybe shell (readline, user sessions?).  

## Who is this for

Everyone using docker who want to build a new image.

**Comment by larsonnn** [comment]
great idea, to keep it simple, we could use the "history" from bash.

you can run your container  with 
- `docker run -v ./bash_history:/root/.bash_history -it <image> /bin/bash` 

install your packages and save the history 
- `history -w` 

then we need a tool to format the lines with some `RUN` and remove the commands we don't need like `history` itself

I guess its easy and we would just need a script for that.

But it would require `bash` to be installed.

**Comment by cloudson** [comment]
Thank you for the thought @larsonnn . 
My main concern is `remove the commands we don't need like history itself`. We haven't a history just with successful commands or I didn't find a way to generate it easily.

**Comment by cloudson** [comment]
Cool. Seems that `buildah-commit(1) | Create an image from a working container.` is exactly what I was looking for. I gonna test it. Thank you @braun1928  .

**Comment by milhomem** [comment]
There are many things that can go wrong with this tool e.g. interactive commands and defining image layers and cleanup instructions.

Can you please enumerate why the current approach to build images is bad and what are you trying to fix?

Also, knowing that this tool will have a lot of limitations what's the minimum goal you want to achieve that would make this tool useful?

**Comment by 21stio** [comment]
I'm not sure if I understand you correctly. But I think `docker commit` is what you are looking for

https://docs.docker.com/engine/reference/commandline/commit/

**Comment by larsonnn** [comment]
So the main idea is to copy the commands you will have in your Dockerfile outside from your "docker run" shell.

Workflow would be:
1. docker run -it ubuntu bash
2. apt-get install nginx <- you want this to be saved
3. apt-get install nginx2 <- this will fail you dont want this
4. exit
5. now there is a magic created file with your successfull commands. ;)

I guess thats the theoretical workflow.?!

this can be done with simple scripting and you don't need to have `buildah`.

you can work with `bash traps` or the `PROMPT_COMMAND` env. Or just run all commands with a prefix.

Im still a friend of using some scripts instead of software like `buildah` just for my prototyping etc.

**Comment by augustohp** [comment]
I am [a bit late][1] to the party but I think this solves the issue: https://github.com/augustohp/ship

[1]: https://twitter.com/augustohp/status/1169247744017321984

**Comment by larsonnn** [comment]
> I am [a bit late](https://twitter.com/augustohp/status/1169247744017321984) to the party but I think this solves the issue: https://github.com/augustohp/ship

never to late

**Comment by cloudson** [comment]
It seems that we have one less idea on this repository 😄. 
Thanks for everyone who joined the discussion and @augustohp for make it happen.
